### ISSUE TITLE
logo in vector graphics? logo in darktheme?

### ISSUE THREAD

**Issue by xgui3783** [HumanBrainProject/openMINDS#16]
I noticed that logo in `/img` is in png format. Whilst it is a lossless format, it is still pixel based. 

Ideally we can provide vector based (e.g. svg) for larger prints

Also, ideally the logo can be available in dark theme.

I understand this is not of high priority, but the longer it waits, the more difficult it gets to retrieve the original file(s).

**Comment by lzehl** [comment]
@xgui3783 I agree! We should provide several options here. We'll take care of it when there is a bit of free time in the near future.

**Comment by lzehl** [comment]
@UlrikeS91 if you have the time, could you prepare a dark theme version for all logo variations? And maybe a logo for the openMINDS instances repo? 

I'll take care of the SVGs. I've prepared them already with equal sizes and margins (etc) locally on my desk.

**Comment by UlrikeS91** [comment]
> @UlrikeS91 if you have the time, could you prepare a dark theme version for all logo variations? And maybe a logo for the openMINDS instances repo?
> 
> I'll take care of the SVGs. I've prepared them already with equal sizes and margins (etc) locally on my desk.

It won't be my first priority, but yes. I'll prepare a dark-themed version as well :) Thanks, @xgui3783 for suggesting this. It's a great idea!

**Comment by UlrikeS91** [comment]
@lzehl I(/we) fixed the dark-themed version. I think we still need to upload all of them (normal logo png + svg & dark-themed logo png + svg). I'll check and upload them.

**Comment by lzehl** [comment]
@UlrikeS91 yes, feel free to upload them. Just make sure to have the same size/resolution as the one already present. Feel free to add more formats for all versions.
