### ISSUE TITLE
add a code of conduct

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS#4]
We should add a code of conduct to all repositories. We can use for example this one as template:
https://www.contributor-covenant.org/version/1/4/code-of-conduct/

@olinux & @skoehnen & @UlrikeS91 could you have a look? what do you think?

**Comment by skoehnen** [comment]
This code of conduct looks good to me.
Under Enforcement it brings up the point of a central contact mail address, which is also something we should discuss.

Do we have some point of contact we could use for this?
The Curation support mail address comes to mind, but I am not sure if these repositories is something we want to route through there.

I can organise a new service mail-adress or mailinglist from the research center, but then it would be in the fzj domain.
It would be cool if we could get an ebrains address.

**Comment by xgui3783** [comment]
speaking of an ebrains address, during TC weekly, it seems possible to set up at ebrains.eu email address, with pop3/imap and smtp servers.

We need to contact marc re: setting it up.

**Comment by skoehnen** [comment]
> speaking of an ebrains address, during TC weekly, it seems possible to set up at ebrains.eu email address, with pop3/imap and smtp servers.
Ah yes, now that you say it, I remember the SMTP discussion.

**Comment by apdavison** [comment]
Maybe this issue could be raised more generally in EBRAINS - perhaps the Diversity and Equal Opportunities Committee would be willing to act as a neutral party for receiving reports of Code of Conduct violations across multiple projects?

**Comment by lzehl** [comment]
@apdavison this is a good idea. You know who to contact for this? Independent of the code of conduct we'll plan to get an openminds-support email.

**Comment by skoehnen** [comment]
I think Karin Grasenick does this for SGA3, I will check.

**Comment by skoehnen** [comment]
> I think Karin Grasenick does this for SGA3, I will check.

https://www.humanbrainproject.eu/en/about/gender-equality/#_contact
