### ISSUE TITLE
Question: defining Person contributions to a dataset

### ISSUE THREAD

**Issue by stevewds** [HumanBrainProject/openMINDS#48]
Hi - 

What is the best way to express: "Person A contributed *data collection* to Dataset A"?

I know how to create a person object and a dataset object and a contribution object that says "Person A contributed *data collection*". But if there are several datasets, and Person A made different contributions to different datasets, I don't know how to properly express that situation in openMINDs.

Thanks!
Steve

**Comment by lzehl** [comment]
@stevewds you can achieve this by creating one Contribution per Person (with multiple roles if needed) per DatasetVersion. Example (simplified):

**DatasetVersion-A**
+ otherContribution: links to Contribution-A-1

**Contribution-A-1**
+ contributor: links to Person-1
+ type: links to [coordination, data collection]

**DatasetVersion-B**
+ otherContribution: links to Contribution-B-1

**Contribution-B-1**
+ contributor: links to Person-1 (same object as above)
+ type: links to [data management, data processing, marketing]

**Comment by stevewds** [comment]
Thanks @lzehl, this answers it.
