### ISSUE TITLE
Question: can one add additional digital identifiers to LivePaper?

### ISSUE THREAD

**Issue by stevewds** [HumanBrainProject/openMINDS#51]
A LivePaper has a single digitalIdentifier, the DOI, which makes sense to me.

Many papers also have a PubMed ID or PubMedCentral ID. I'd like to add those quantities to a LivePaper. Is there a straightforward way to do that?

Thanks
Steve

**Comment by lzehl** [comment]
@apdavison could you take this one over?

**Comment by apdavison** [comment]
I think this would also apply to ScholarlyArticle, and perhaps also to Book and Chapter.

We could add additional widely-used identifiers like PubMed IDs in openMINDS_core, and/or we could add a GenericDigitalIdentifier which requires you to specify the Organization that emits the identifiers. (For example, in France we also have to upload all our publications to the national archive, HAL, which has its own identifiers; we probably don't want to add a separate schema identifier for every national or university-level repository).

**Comment by stevewds** [comment]
I like the idea of a GenericDigitalIdentifier, and it is well motivated by the reasons you describe.
