### ISSUE TITLE
Name too long?

### ISSUE THREAD

**Issue by olinux** [HumanBrainProject/openMINDS#8]
I was wondering if we should really strive for this long names and not only call it "IANA reference" and put the resolution of the acronym into the description!? 

https://github.com/HumanBrainProject/openMINDS/blob/d492dd5d4eb5e643c077774bd7d2262b5c70c13a/vocab/properties.json#L866

**Comment by lzehl** [comment]
Yes. Property names should be as short as possible (providing enough idea what they are about, but not necessarily self explanatory. the full explanation can be provided in the descriptions as you said) . 

I'll have a look and make a plan which could be shortened.
